[workspace]
members = [
    "ffmpeg-cluster-common",
    "ffmpeg-cluster-server",
    "ffmpeg-cluster-client"
]
resolver = "2"

[workspace.package]
version = "0.2.4"
edition = "2021"
authors = ["Denis Sandalini <denis@novux.tech>"]
